version: '3.1'

services:
  mongo:
    image: mongo:latest
    restart: always
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      PUID: 1000
      PGID: 1000
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    deploy:
      replicas: 1

  flask:
    build: ./docker/flask
    restart: always
    ports:
      - "80:80"
    depends_on:
      - mongo
volumes:
  mongodb:
